apiVersion: v1
kind: Service
metadata:
  name: complaint
spec:
  selector:
    name: complaint
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: complaint
spec:
  selector:
    matchLabels:
      name: complaint
  replicas: 1
  template:
    metadata:
      labels:
        name: complaint
    spec:
      containers:
      - name: complaint
        image: complaint-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MONGODB_IP
          value: localhost:27017
        - name: PORT
          value: "3000"
        ports:
          - containerPort: 3000
      - name: mongo
        image: mongo
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
          - containerPort: 27017
      hostname: complaint
---
apiVersion: v1
kind: Service
metadata:
  name: department
spec:
  selector:
    name: department
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
spec:
  selector:
    matchLabels:
      name: department
  replicas: 1
  template:
    metadata:
      labels:
        name: department
    spec:
      containers:
      - name: department
        image: department-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DATASOURCE_PORT
          value: "3306"
        - name: DATASOURCE_HOST
          value: localhost
        - name: DATASOURCE_USERNAME
          value: root
        - name: DATASOURCE_PASSWORD
          value: password
        - name: DATASOURCE_DATABASE
          value: test
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
      - name: department-db
        image: dep-mysql
        resources: 
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: issue
spec:
  selector:
    name: issue
  ports:
  - port: 9009
    targetPort: 9009
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: issue
spec:
  selector:
    matchLabels:
      name: issue
  replicas: 1
  template:
    metadata:
      labels:
        name: issue
    spec:
      containers:
      - name: issue
        image: ims-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DATASOURCE_URL
          value: "jdbc:postgresql://localhost:5432/postgres"
        - name: DATASOURCE_USERNAME
          value: postgres
        - name: DATASOURCE_PASSWORD
          value: password
        - name: SERVER_PORT
          value: "9009"
        ports:
        - containerPort: 9009
      - name: imsdb
        image: postgres
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: POSTGRES_PASSWORD
          value: password
---

# apiVersion: v1
# kind: Service
# metadata:
#   name: app-fe
# spec:
#   selector:
#     app: wonky
#   ports:
#   - port: 80
#     targetPort: 80

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-fe
# spec:
#   selector:
#     matchLabels:
#       name: wonky
#   template:
#     metadata:
#       labels:
#         name: wonky-fe
#     spec:
#       containers:
#       - name: wonky-fe
#         image: wonky-fe
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
#         ports:
#         - containerPort: 80

# apiVersion: v1
# kind: Service
# metadata:
#   name: command-central
# spec:
#   selector:
#     name: command-central
#   ports:
#   - port: 80
#     targetPort: 8080

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: command-central
# spec:
#   selector:
#     matchLabels:
#       name: command-central
#   template:
#     metadata:
#       labels:
#         name: command-central
#     spec:
#       containers:
#       - name: command-central
#         image: command-central
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
#         ports:
#         - containerPort: 8080




